name: ${project.name}
version: ${project.version}
main: me.sizzlemcgrizzle.blueprints.BlueprintsPlugin
author: sizzlemcgrizzle
api-version: 1.13
description: Place "blueprint" blocks to build schematics!
softdepend: [CLClans, WorldEdit, WorldGuard]
permissions:
  blueprints.create.color:
    default: op
  blueprints.create:
    default: true
  blueprints.add:
    default: op
  blueprints.remove:
    default: op
  blueprints.reload:
    default: op
  blueprints.list:
    default: op
  blueprints.get:
    default: op
  blueprints.addtype:
    default: op
commands:
  blueprints:
    description: Main blueprints command group
  blueprint:
    description: Command to create a player blueprint

